"""terminal.kitty — kitty, pywal-themed via kitty-colorizer.py, 0.75 opacity

current-theme.conf is regenerated by desktop.theming; kitty.conf pins
/bin/zsh.
"""

from __future__ import annotations

from .setup import FeatureSetup, SetupStep

SETUP = FeatureSetup(
    feature_id="terminal.kitty",
    steps=(
    ),
)
