# vim:ft=kitty
# Kitty theme template — filled by kitty-colorizer.py from pywal colors.

# The basic colors
foreground              #debda8
background              #110d0a
selection_foreground    #110d0a
selection_background    #debda8

# Cursor colors
cursor                  #debda8
cursor_text_color       #110d0a

# URL underline color when hovering with mouse
url_color               #986A51

# Kitty window border colors
active_border_color     #986A51
inactive_border_color   #9b8475
bell_border_color       #CF6234

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #110d0a
active_tab_background   #B66E4A
inactive_tab_foreground #debda8
inactive_tab_background #110d0a
tab_bar_background      #110d0a

# Colors for marks (marked text in the terminal)
mark1_foreground #110d0a
mark1_background #986A51
mark2_foreground #110d0a
mark2_background #B66E4A
mark3_foreground #110d0a
mark3_background #B49774

# The 16 terminal colors

# black
color0 #110d0a
color8 #9b8475

# red
color1 #A85932
color9 #A85932

# green
color2  #C9572D
color10 #C9572D

# yellow
color3  #CF6234
color11 #CF6234

# blue
color4  #986A51
color12 #986A51

# magenta
color5  #B66E4A
color13 #B66E4A

# cyan
color6  #B49774
color14 #B49774

# white
color7  #debda8
color15 #debda8
