# vim:ft=kitty
# Kitty theme template — filled by kitty-colorizer.py from pywal colors.

# The basic colors
foreground              #c7e9ee
background              #101314
selection_foreground    #101314
selection_background    #c7e9ee

# Cursor colors
cursor                  #c7e9ee
cursor_text_color       #101314

# URL underline color when hovering with mouse
url_color               #5CA4D5

# Kitty window border colors
active_border_color     #5CA4D5
inactive_border_color   #8ba3a6
bell_border_color       #BD6B8E

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #101314
active_tab_background   #919B9F
inactive_tab_foreground #c7e9ee
inactive_tab_background #101314
tab_bar_background      #101314

# Colors for marks (marked text in the terminal)
mark1_foreground #101314
mark1_background #5CA4D5
mark2_foreground #101314
mark2_background #919B9F
mark3_foreground #101314
mark3_background #D6C7AE

# The 16 terminal colors

# black
color0 #101314
color8 #8ba3a6

# red
color1 #627894
color9 #627894

# green
color2  #386FCC
color10 #386FCC

# yellow
color3  #BD6B8E
color11 #BD6B8E

# blue
color4  #5CA4D5
color12 #5CA4D5

# magenta
color5  #919B9F
color13 #919B9F

# cyan
color6  #D6C7AE
color14 #D6C7AE

# white
color7  #c7e9ee
color15 #c7e9ee
