# vim:ft=kitty
# Kitty theme template — filled by kitty-colorizer.py from pywal colors.

# The basic colors
foreground              #e8c7bc
background              #321f28
selection_foreground    #321f28
selection_background    #e8c7bc

# Cursor colors
cursor                  #e8c7bc
cursor_text_color       #321f28

# URL underline color when hovering with mouse
url_color               #5982BD

# Kitty window border colors
active_border_color     #5982BD
inactive_border_color   #a28b83
bell_border_color       #CA7883

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #321f28
active_tab_background   #5883C0
inactive_tab_foreground #e8c7bc
inactive_tab_background #321f28
tab_bar_background      #321f28

# Colors for marks (marked text in the terminal)
mark1_foreground #321f28
mark1_background #5982BD
mark2_foreground #321f28
mark2_background #5883C0
mark3_foreground #321f28
mark3_background #A9919B

# The 16 terminal colors

# black
color0 #321f28
color8 #a28b83

# red
color1 #5176B5
color9 #5176B5

# green
color2  #AC6B8B
color10 #AC6B8B

# yellow
color3  #CA7883
color11 #CA7883

# blue
color4  #5982BD
color12 #5982BD

# magenta
color5  #5883C0
color13 #5883C0

# cyan
color6  #A9919B
color14 #A9919B

# white
color7  #e8c7bc
color15 #e8c7bc
